### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Moriarty900** [griffenx/Apex-Launcher#1]
First of all: AWESOME GAME

Only bug i found was at the beginning Griffen leads us to this abandoned house and when he enters 
the door, i entered too but my character slipt through the wall (i think 4 spaces left of the door)

**Comment by griffenx** [comment]
this is the repository for the game's launcher only. please report all bugs with the game itself to the official subreddit: https://www.reddit.com/r/PokemonApex/wiki/issue-reporting
