### ISSUE TITLE
Launcher Crash

### ISSUE THREAD

**Issue by Advtech92** [griffenx/Apex-Launcher#11]
Steps to replicate error:
------
1. Open launcher
2. Click on start game
3.  Game not found error message
4. Click yes to download
5. Begins download
6. Crash
-----
Image of the error is attached.
![screenshot 2](https://cloud.githubusercontent.com/assets/2319526/23406155/9b5acf96-fd8b-11e6-814d-d86e612b3345.png)
-----
Please feel free to let me know if you need anymore info.
This occurred during save file load

**Comment by griffenx** [comment]
Alright. Since there doesn't seem to be an exception encountered, I'm going to need some more information about your environment:

* Can you post the contents of your `config.txt` file? It should be located in the same directory as the Launcher's executable.
* Did you recently change the Install Path variable? If so, this might be the cause.

**Comment by Advtech92** [comment]
I did just move the game to a new folders to see if it works now. I shall reply once I test it

**Comment by griffenx** [comment]
A similar issue was reported in #10 , so this is likely the cause of your issue.

**Comment by Advtech92** [comment]
Still having a crash issue. 
Here's the contents of the config.txt
currentversion=ALPHA 0.0
currentlauncherversion=0.0.1
installpath=
keepLauncherOpen=false
disableGameFonts=false

**Comment by griffenx** [comment]
Alright. So what's your file system look like right now with regards to the launcher? Did you move the launcher's .exe file, or did you move all the data as well?

Ideally, in the folder where the launcher's .exe is located (or in the folder corresponding to your `installpath` variable), there should be the `config.txt` as well as a folder called `Versions` that should have subfolders for each version of the game.

If you moved either the .exe or the `Versions` folder, you will need to do one of the following:
* Move the `Versions` folder to the location of the .exe
* Set the `installpath` variable to the location of the `Versions` folder

Let me know if any of this makes a difference.

**Comment by Advtech92** [comment]
Finally managed to get it to work.

**Comment by griffenx** [comment]
Would you mind describing how you were able to resolve the issue?
