### ISSUE TITLE
String to Decimal conversion fails

### ISSUE THREAD

**Issue by diogoeiras** [griffenx/Apex-Launcher#13]
If the running computer has a culture where the decimal symbol is not a dot, the conversion will fail.

**Comment by griffenx** [comment]
I think specifically this is referring to parsing version numbers from the version manifest and config, which I believe are the only places where the conversion from String to Double is performed. I'll push out a commit for this when I get home today.

**Comment by diogoeiras** [comment]
I can confirm you that at least it fails when converting from the config.txt file.

**Comment by griffenx** [comment]
I believe that I've fixed this issue, but I can't test it on my own computer, since I can't change the system locale (to my knowledge). Would you be willing to test a new version of the program to make sure these changes work?

**Comment by diogoeiras** [comment]
I think you can close this one. I tested a clean version of the project and it gave no errors this time.

**Comment by griffenx** [comment]
This should be fixed in v1.4.1.
