### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by DarkGalahad** [griffenx/Apex-Launcher#15]
![apex](https://cloud.githubusercontent.com/assets/28794160/26226997/97317b94-3bfd-11e7-839d-85d78c2e1b32.PNG)

Whenever I open up the launcher, I get this particular error. I've been playing the game for 2 days now, and this error just popped up randomly, trying to open up the launcher now, and I don't know why

**Comment by griffenx** [comment]
Please expand the Details section of that error and provide me the included text.

**Comment by griffenx** [comment]
Since no information has been provided, I'm closing this issue.
