### ISSUE TITLE
New Launcher Version Available?

### ISSUE THREAD

**Issue by Jps101** [griffenx/Apex-Launcher#16]
I have downloaded Launcher Version v1.4.1 however when I try to open it, I get a message saying -

New Launcher Version is available: v1.4.1. Would you like to download it now?

If I hit yes, it opens the github page and the launcher but the launcher looks like below:
![image](https://cloud.githubusercontent.com/assets/5391182/26285136/894d7668-3e41-11e7-9a65-759b9aa72bc8.png)

If I hit no, it loads the launcher normally.

**Comment by griffenx** [comment]
This is likely due to a mistake I made in labeling the new version here on GitHub. This should be fixed now.

**Comment by griffenx** [comment]
Upon further inspection, it appears that I was using an incorrect property to check the third-tier version of the local copy of the launcher, so this bug was persisting. I have fixed this, and it will be patched in the next version of the launcher.
