### ISSUE TITLE
I can't get the game to start.

### ISSUE THREAD

**Issue by TheShadolo** [griffenx/Apex-Launcher#19]
So I downloaded the launcher from http://apex.iamvishnu.net/ . It says it is File version 1.4.3. It's telling me that it can't connect to the internet, but I'm using the internet right now to post this. 

When I click the Launch Game button, a window pops up telling me that the launcher can't find the game in it's install path, and that I might have moved or deleted it, then asks if I want to redownload it. I click "Yes," and another window pops up telling me that the installer couldn't find "VersionManifest.xml".

Did I download the wrong thing? Or am I just missing something obvious?

**Comment by griffenx** [comment]
The launcher tests your network connectivity by attempting to download the Version Manifest (an XML file containing information for each version of the game). This file is hosted by Mediafire, and you can find it here: http://www.mediafire.com/download/qkauu9oca3lcjw1/VersionManifest.xml

See if you can download it manually.

**Comment by TheShadolo** [comment]
That seems to have cleared everything up. There are now images on the launcher, and the game is updating to ALPHA 7 as I write this. THank you very much for your quick response!
