### ISSUE TITLE
Launcher Bug

### ISSUE THREAD

**Issue by Craxuan** [griffenx/Apex-Launcher#2]
![image](https://cloud.githubusercontent.com/assets/20674130/17162559/9d3a7e66-53e9-11e6-9d55-1b7c6b09527e.png)

**Comment by griffenx** [comment]
It looks like this is an issue with the zip file that was uploaded. Not sure why, but it's showing as invalid now. I'll reupload it and that should fix this issue.
I'll also add an error handler for this issue so that I'll know if it happens again.

**Comment by griffenx** [comment]
This should be solved in the latest commit. The next version of the launcher will contain this fix.

**Comment by griffenx** [comment]
This issue does not appear to be persisting, so I'm going to close it.
