### ISSUE TITLE
Crashs after added a weather widget (Huawei Mate 10 / EMUI 8)

### ISSUE THREAD

**Issue by bgn9000** [griffenx/Apex-Launcher#23]
Hi, I added the widget and it crashed then each time I am trying to run it crashs again.
Any recovery mode?

**Comment by bgn9000** [comment]
Recovery done after reinstallation and reload backups. All good now. 
However, you can provide a way to skip widgets load in the settings.
Another little issue with Huawei is the lack of menu button that makes settings a little bit difficult to find. Hope the best with this nice app.

**Comment by griffenx** [comment]
I think you might have the wrong repo, bud.
