### ISSUE TITLE
launcher not showing the launch game option

### ISSUE THREAD

**Issue by weeb-destroyer** [griffenx/Apex-Launcher#28]

**Comment by griffenx** [comment]
I believe this should be fixed as of the latest commit. Please test the updated build of the launcher below and confirm if the issue is resolved.
[Apex Launcher.zip](https://github.com/griffenx/Apex-Launcher/files/3018645/Apex.Launcher.zip)

**Comment by griffenx** [comment]
Additional testers have confirmed that this issue has been resolved in v1.4.5
