### ISSUE TITLE
Script Mistake

### ISSUE THREAD

**Issue by Craxuan** [griffenx/Apex-Launcher#3]
It should be, "I dunno where you're from'.

![image](https://cloud.githubusercontent.com/assets/20674130/17163316/b04ec14a-53f0-11e6-915c-c9a7386c6a4e.png)

**Comment by griffenx** [comment]
Issues with the game itself should be reported on the subreddit.

This is also the intended phrasing. Larry is saying "I don't know how things are done in wherever it is that you're from, but here in Abbadon..."

**Comment by Craxuan** [comment]
Oh - oh. >_> Well that's embarrassing. Alright.
