### ISSUE TITLE
Pokemon Apex Tumblr Home Page 'Downloads Page' Error

### ISSUE THREAD

**Issue by Craxuan** [griffenx/Apex-Launcher#4]
If I click this link:

![bugapex3-1](https://cloud.githubusercontent.com/assets/20674130/17163549/2bbbb0fc-53f3-11e6-9825-12fd37fe6feb.png)

It will come out this. Tested on both Chrome and Edge:

![bugapex3-2](https://cloud.githubusercontent.com/assets/20674130/17163561/4096552c-53f3-11e6-8d40-c7509e834bd2.png)

**Comment by griffenx** [comment]
Tumblr fucked up the markdown when I originally published the post. i have it fixed now.

Please ONLY report issues with the launcher here.
