### ISSUE TITLE
Launcher Refuses To Run (Win10)

### ISSUE THREAD

**Issue by JashSpacy** [griffenx/Apex-Launcher#6]
When I try to run the Apex Launcher, after downloading from GITHUB, I run into several issues.  The same issues occur when trying to run the game manually.  Please see the semi-sarcastic image link posted below which also shows the properties and errors.
---
http://imgur.com/a/gZgad

**Comment by griffenx** [comment]
A quick google search of your error message shows that this is almost certainly a Windows issue. Try following [this guide](https://support.microsoft.com/en-us/kb/2669244) to see if you can troubleshoot the problem.

**Comment by JashSpacy** [comment]
Thank you for the link, but none of those solutions are helping, as there is no shortcut(launcher is on desktop), and my profile has full control.

**Comment by griffenx** [comment]
You should also check to see if any antivirus programs (including Windows Defender) are blocking it from running. I'm 95% sure that this is a Windows issue and not a launcher issue. I can try to help you through it, but I'm going to go ahead and mark this as a non-issue.

**Comment by JashSpacy** [comment]
Fantastic-ish news!  Turns out that the game DOES experience issues with certain antivirus software.  My issue was with PandaAntivirus.  The free version would not let me make exceptions for unlicensed software.  Thanks again for the suggestions and all the help.

**Comment by griffenx** [comment]
That'll do it. 7 out of 10 times, if there's a weird issue like this, the culprit is antivirus. I'll go ahead and close this issue.
